directive set /SysTop/InputSetup/InputSetup:MemoryRun/MemoryRun/crossbar<InputSetup::InputType,8U,8U>:for:land#7.lpi#1 REGISTER_NAME crossbar<InputSetup::InputType,8U,8U>:for:land#7.lpi#1
directive set /SysTop/InputSetup/InputSetup:MemoryRun/MemoryRun/crossbar<InputSetup::InputType,8U,8U>:for:land#7.lpi#1.dfm#1.1 REGISTER_NAME crossbar<InputSetup::InputType,8U,8U>:for:land#7.lpi#1
directive set /SysTop/InputSetup/InputSetup:MemoryRun/MemoryRun/crossbar<InputSetup::InputType,8U,8U>:for:land#6.lpi#1 REGISTER_NAME crossbar<InputSetup::InputType,8U,8U>:for:land#6.lpi#1
directive set /SysTop/InputSetup/InputSetup:MemoryRun/MemoryRun/crossbar<InputSetup::InputType,8U,8U>:for:land#6.lpi#1.dfm#1.1 REGISTER_NAME crossbar<InputSetup::InputType,8U,8U>:for:land#6.lpi#1
directive set /SysTop/InputSetup/InputSetup:MemoryRun/MemoryRun/crossbar<InputSetup::InputType,8U,8U>:for:land#5.lpi#1 REGISTER_NAME crossbar<InputSetup::InputType,8U,8U>:for:land#5.lpi#1
directive set /SysTop/InputSetup/InputSetup:MemoryRun/MemoryRun/crossbar<InputSetup::InputType,8U,8U>:for:land#5.lpi#1.dfm#1.1 REGISTER_NAME crossbar<InputSetup::InputType,8U,8U>:for:land#5.lpi#1
directive set /SysTop/InputSetup/InputSetup:MemoryRun/MemoryRun/crossbar<InputSetup::InputType,8U,8U>:for:land#4.lpi#1 REGISTER_NAME crossbar<InputSetup::InputType,8U,8U>:for:land#4.lpi#1
directive set /SysTop/InputSetup/InputSetup:MemoryRun/MemoryRun/crossbar<InputSetup::InputType,8U,8U>:for:land#4.lpi#1.dfm#1.1 REGISTER_NAME crossbar<InputSetup::InputType,8U,8U>:for:land#4.lpi#1
directive set /SysTop/InputSetup/InputSetup:MemoryRun/MemoryRun/crossbar<InputSetup::InputType,8U,8U>:for:land#3.lpi#1 REGISTER_NAME crossbar<InputSetup::InputType,8U,8U>:for:land#3.lpi#1
directive set /SysTop/InputSetup/InputSetup:MemoryRun/MemoryRun/crossbar<InputSetup::InputType,8U,8U>:for:land#3.lpi#1.dfm#1.1 REGISTER_NAME crossbar<InputSetup::InputType,8U,8U>:for:land#3.lpi#1
directive set /SysTop/InputSetup/InputSetup:MemoryRun/MemoryRun/crossbar<InputSetup::InputType,8U,8U>:for:land#2.lpi#1 REGISTER_NAME crossbar<InputSetup::InputType,8U,8U>:for:land#2.lpi#1
directive set /SysTop/InputSetup/InputSetup:MemoryRun/MemoryRun/crossbar<InputSetup::InputType,8U,8U>:for:land#2.lpi#1.dfm#1.1 REGISTER_NAME crossbar<InputSetup::InputType,8U,8U>:for:land#2.lpi#1
directive set /SysTop/InputSetup/InputSetup:MemoryRun/MemoryRun/crossbar<InputSetup::InputType,8U,8U>:for:land#1.lpi#1 REGISTER_NAME crossbar<InputSetup::InputType,8U,8U>:for:land#1.lpi#1
directive set /SysTop/InputSetup/InputSetup:MemoryRun/MemoryRun/crossbar<InputSetup::InputType,8U,8U>:for:land#1.lpi#1.dfm#1.1 REGISTER_NAME crossbar<InputSetup::InputType,8U,8U>:for:land#1.lpi#1
directive set /SysTop/SysPE/SysPE:PERun/PERun/weight_reg.sva REGISTER_NAME weight_reg.sva
directive set /SysTop/SysPE/SysPE:PERun/PERun/weight_reg.sva.dfm.1 REGISTER_NAME weight_reg.sva
