// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    10.4b/841621 Production Release
//  HLS Date:       Thu Oct 24 17:20:07 PDT 2019
// 
//  Generated by:   billyk@cad.eecs.harvard.edu
//  Generated date: Sun May  3 14:21:25 2020
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    Connections_Combinational_SysPE_AccumType_Connections_SYN_PORT_PushNB_core
// ------------------------------------------------------------------


module Connections_Combinational_SysPE_AccumType_Connections_SYN_PORT_PushNB_core
    (
  this_val, this_rdy, return_rsc_z, ccs_ccore_start_rsc_dat, ccs_MIO_clk, ccs_MIO_arst
);
  output this_val;
  reg this_val;
  input this_rdy;
  output return_rsc_z;
  input ccs_ccore_start_rsc_dat;
  input ccs_MIO_clk;
  input ccs_MIO_arst;


  // Interconnect Declarations
  wire ccs_ccore_start_rsci_idat;
  reg asn_itm_1;


  // Interconnect Declarations for Component Instantiations 
  mgc_out_dreg_v2 #(.rscid(32'sd18),
  .width(32'sd1)) return_rsci (
      .d(this_rdy),
      .z(return_rsc_z)
    );
  ccs_in_v1 #(.rscid(32'sd211),
  .width(32'sd1)) ccs_ccore_start_rsci (
      .dat(ccs_ccore_start_rsc_dat),
      .idat(ccs_ccore_start_rsci_idat)
    );
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      this_val <= 1'b0;
    end
    else if ( ccs_ccore_start_rsci_idat | asn_itm_1 ) begin
      this_val <= ccs_ccore_start_rsci_idat;
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      asn_itm_1 <= 1'b0;
    end
    else begin
      asn_itm_1 <= ccs_ccore_start_rsci_idat;
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    Connections_Combinational_SysPE_AccumType_Connections_SYN_PORT_PushNB
// ------------------------------------------------------------------


module Connections_Combinational_SysPE_AccumType_Connections_SYN_PORT_PushNB (
  this_val, this_rdy, this_msg, return_rsc_z, ccs_ccore_start_rsc_dat, ccs_MIO_clk,
      ccs_MIO_arst
);
  output this_val;
  input this_rdy;
  output [31:0] this_msg;
  output return_rsc_z;
  input ccs_ccore_start_rsc_dat;
  input ccs_MIO_clk;
  input ccs_MIO_arst;



  // Interconnect Declarations for Component Instantiations 
  Connections_Combinational_SysPE_AccumType_Connections_SYN_PORT_PushNB_core Connections_Combinational_SysPE_AccumType_Connections_SYN_PORT_PushNB_core_inst
      (
      .this_val(this_val),
      .this_rdy(this_rdy),
      .return_rsc_z(return_rsc_z),
      .ccs_ccore_start_rsc_dat(ccs_ccore_start_rsc_dat),
      .ccs_MIO_clk(ccs_MIO_clk),
      .ccs_MIO_arst(ccs_MIO_arst)
    );
  assign this_msg = 32'b00000000000000000000000000000000;
endmodule



