// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    10.4b/841621 Production Release
//  HLS Date:       Thu Oct 24 17:20:07 PDT 2019
// 
//  Generated by:   billyk@cad.eecs.harvard.edu
//  Generated date: Fri Apr 17 23:10:03 2020
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    Connections_Combinational_ArbitratedScratchpad_InputSetup_InputType_256U_8U_8U_0U_req_t_Connections_SYN_PORT_PushNB_core
// ------------------------------------------------------------------


module Connections_Combinational_ArbitratedScratchpad_InputSetup_InputType_256U_8U_8U_0U_req_t_Connections_SYN_PORT_PushNB_core
    (
  this_val, this_rdy, this_msg, m_valids_rsc_dat, m_addr_rsc_dat, return_rsc_z, ccs_ccore_start_rsc_dat,
      ccs_MIO_clk, ccs_MIO_arst
);
  output this_val;
  reg this_val;
  input this_rdy;
  output [136:0] this_msg;
  input [7:0] m_valids_rsc_dat;
  input [63:0] m_addr_rsc_dat;
  output return_rsc_z;
  input ccs_ccore_start_rsc_dat;
  input ccs_MIO_clk;
  input ccs_MIO_arst;


  // Interconnect Declarations
  wire [7:0] m_valids_rsci_idat;
  wire [63:0] m_addr_rsci_idat;
  wire ccs_ccore_start_rsci_idat;
  reg wm_val_Marshall_137U_for_8_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1;
  reg [7:0] wm_val_Marshall_137U_for_8_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1;
  reg wm_val_Marshall_137U_for_7_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1;
  reg [7:0] wm_val_Marshall_137U_for_7_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1;
  reg wm_val_Marshall_137U_for_6_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1;
  reg [7:0] wm_val_Marshall_137U_for_6_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1;
  reg wm_val_Marshall_137U_for_5_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1;
  reg [7:0] wm_val_Marshall_137U_for_5_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1;
  reg wm_val_Marshall_137U_for_4_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1;
  reg [7:0] wm_val_Marshall_137U_for_4_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1;
  reg wm_val_Marshall_137U_for_3_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1;
  reg [7:0] wm_val_Marshall_137U_for_3_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1;
  reg wm_val_Marshall_137U_for_2_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1;
  reg [7:0] wm_val_Marshall_137U_for_2_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1;
  reg wm_val_Marshall_137U_for_1_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1;
  reg [7:0] wm_val_Marshall_137U_for_1_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1;
  reg asn_itm_1;


  // Interconnect Declarations for Component Instantiations 
  ccs_in_v1 #(.rscid(32'sd234),
  .width(32'sd8)) m_valids_rsci (
      .dat(m_valids_rsc_dat),
      .idat(m_valids_rsci_idat)
    );
  ccs_in_v1 #(.rscid(32'sd235),
  .width(32'sd64)) m_addr_rsci (
      .dat(m_addr_rsc_dat),
      .idat(m_addr_rsci_idat)
    );
  mgc_out_dreg_v2 #(.rscid(32'sd237),
  .width(32'sd1)) return_rsci (
      .d(this_rdy),
      .z(return_rsc_z)
    );
  ccs_in_v1 #(.rscid(32'sd318),
  .width(32'sd1)) ccs_ccore_start_rsci (
      .dat(ccs_ccore_start_rsc_dat),
      .idat(ccs_ccore_start_rsci_idat)
    );
  assign this_msg = {1'b0 , wm_val_Marshall_137U_for_8_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
      , wm_val_Marshall_137U_for_8_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
      , 8'b00000000 , wm_val_Marshall_137U_for_7_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
      , wm_val_Marshall_137U_for_7_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
      , 8'b00000000 , wm_val_Marshall_137U_for_6_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
      , wm_val_Marshall_137U_for_6_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
      , 8'b00000000 , wm_val_Marshall_137U_for_5_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
      , wm_val_Marshall_137U_for_5_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
      , 8'b00000000 , wm_val_Marshall_137U_for_4_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
      , wm_val_Marshall_137U_for_4_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
      , 8'b00000000 , wm_val_Marshall_137U_for_3_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
      , wm_val_Marshall_137U_for_3_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
      , 8'b00000000 , wm_val_Marshall_137U_for_2_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
      , wm_val_Marshall_137U_for_2_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
      , 8'b00000000 , wm_val_Marshall_137U_for_1_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
      , wm_val_Marshall_137U_for_1_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
      , 8'b00000000};
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      this_val <= 1'b0;
    end
    else if ( ccs_ccore_start_rsci_idat | asn_itm_1 ) begin
      this_val <= ccs_ccore_start_rsci_idat;
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      wm_val_Marshall_137U_for_8_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
          <= 1'b0;
      wm_val_Marshall_137U_for_8_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
          <= 8'b00000000;
      wm_val_Marshall_137U_for_7_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
          <= 1'b0;
      wm_val_Marshall_137U_for_7_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
          <= 8'b00000000;
      wm_val_Marshall_137U_for_6_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
          <= 1'b0;
      wm_val_Marshall_137U_for_6_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
          <= 8'b00000000;
      wm_val_Marshall_137U_for_5_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
          <= 1'b0;
      wm_val_Marshall_137U_for_5_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
          <= 8'b00000000;
      wm_val_Marshall_137U_for_4_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
          <= 1'b0;
      wm_val_Marshall_137U_for_4_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
          <= 8'b00000000;
      wm_val_Marshall_137U_for_3_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
          <= 1'b0;
      wm_val_Marshall_137U_for_3_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
          <= 8'b00000000;
      wm_val_Marshall_137U_for_2_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
          <= 1'b0;
      wm_val_Marshall_137U_for_2_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
          <= 8'b00000000;
      wm_val_Marshall_137U_for_1_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
          <= 1'b0;
      wm_val_Marshall_137U_for_1_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
          <= 8'b00000000;
    end
    else if ( ccs_ccore_start_rsci_idat ) begin
      wm_val_Marshall_137U_for_8_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
          <= m_valids_rsci_idat[7];
      wm_val_Marshall_137U_for_8_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
          <= m_addr_rsci_idat[63:56];
      wm_val_Marshall_137U_for_7_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
          <= m_valids_rsci_idat[6];
      wm_val_Marshall_137U_for_7_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
          <= m_addr_rsci_idat[55:48];
      wm_val_Marshall_137U_for_6_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
          <= m_valids_rsci_idat[5];
      wm_val_Marshall_137U_for_6_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
          <= m_addr_rsci_idat[47:40];
      wm_val_Marshall_137U_for_5_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
          <= m_valids_rsci_idat[4];
      wm_val_Marshall_137U_for_5_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
          <= m_addr_rsci_idat[39:32];
      wm_val_Marshall_137U_for_4_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
          <= m_valids_rsci_idat[3];
      wm_val_Marshall_137U_for_4_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
          <= m_addr_rsci_idat[31:24];
      wm_val_Marshall_137U_for_3_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
          <= m_valids_rsci_idat[2];
      wm_val_Marshall_137U_for_3_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
          <= m_addr_rsci_idat[23:16];
      wm_val_Marshall_137U_for_2_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
          <= m_valids_rsci_idat[1];
      wm_val_Marshall_137U_for_2_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
          <= m_addr_rsci_idat[15:8];
      wm_val_Marshall_137U_for_1_type_to_vector_bool_1_slc_this_write_msg_wm_val_valids_1_0_1
          <= m_valids_rsci_idat[0];
      wm_val_Marshall_137U_for_1_to_sc_8_1_v_slc_this_write_msg_wm_val_addr_8_7_0_1
          <= m_addr_rsci_idat[7:0];
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      asn_itm_1 <= 1'b0;
    end
    else begin
      asn_itm_1 <= ccs_ccore_start_rsci_idat;
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    Connections_Combinational_ArbitratedScratchpad_InputSetup_InputType_256U_8U_8U_0U_req_t_Connections_SYN_PORT_PushNB
// ------------------------------------------------------------------


module Connections_Combinational_ArbitratedScratchpad_InputSetup_InputType_256U_8U_8U_0U_req_t_Connections_SYN_PORT_PushNB
    (
  this_val, this_rdy, this_msg, m_valids_rsc_dat, m_addr_rsc_dat, return_rsc_z, ccs_ccore_start_rsc_dat,
      ccs_MIO_clk, ccs_MIO_arst
);
  output this_val;
  input this_rdy;
  output [136:0] this_msg;
  input [7:0] m_valids_rsc_dat;
  input [63:0] m_addr_rsc_dat;
  output return_rsc_z;
  input ccs_ccore_start_rsc_dat;
  input ccs_MIO_clk;
  input ccs_MIO_arst;



  // Interconnect Declarations for Component Instantiations 
  Connections_Combinational_ArbitratedScratchpad_InputSetup_InputType_256U_8U_8U_0U_req_t_Connections_SYN_PORT_PushNB_core
      Connections_Combinational_ArbitratedScratchpad_InputSetup_InputType_256U_8U_8U_0U_req_t_Connections_SYN_PORT_PushNB_core_inst
      (
      .this_val(this_val),
      .this_rdy(this_rdy),
      .this_msg(this_msg),
      .m_valids_rsc_dat(m_valids_rsc_dat),
      .m_addr_rsc_dat(m_addr_rsc_dat),
      .return_rsc_z(return_rsc_z),
      .ccs_ccore_start_rsc_dat(ccs_ccore_start_rsc_dat),
      .ccs_MIO_clk(ccs_MIO_clk),
      .ccs_MIO_arst(ccs_MIO_arst)
    );
endmodule



