// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    10.4b/841621 Production Release
//  HLS Date:       Thu Oct 24 17:20:07 PDT 2019
// 
//  Generated by:   billyk@cad.eecs.harvard.edu
//  Generated date: Fri Apr 17 23:10:20 2020
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    Connections_Combinational_ArbitratedScratchpad_InputSetup_InputType_256U_8U_8U_0U_req_t_Connections_SYN_PORT_PopNB_core
// ------------------------------------------------------------------


module Connections_Combinational_ArbitratedScratchpad_InputSetup_InputType_256U_8U_8U_0U_req_t_Connections_SYN_PORT_PopNB_core
    (
  this_val, this_rdy, this_msg, data_type_val_rsc_z, data_valids_rsc_z, data_addr_rsc_z,
      data_data_rsc_z, return_rsc_z, ccs_ccore_start_rsc_dat, ccs_MIO_clk, ccs_MIO_arst
);
  input this_val;
  output this_rdy;
  reg this_rdy;
  input [136:0] this_msg;
  output data_type_val_rsc_z;
  output [7:0] data_valids_rsc_z;
  output [63:0] data_addr_rsc_z;
  output [63:0] data_data_rsc_z;
  output return_rsc_z;
  input ccs_ccore_start_rsc_dat;
  input ccs_MIO_clk;
  input ccs_MIO_arst;


  // Interconnect Declarations
  wire ccs_ccore_start_rsci_idat;
  reg asn_itm_1;


  // Interconnect Declarations for Component Instantiations 
  wire [0:0] nl_data_type_val_rsci_d;
  assign nl_data_type_val_rsci_d = this_msg[136];
  wire [7:0] nl_data_valids_rsci_d;
  assign nl_data_valids_rsci_d = {(this_msg[135]) , (this_msg[118]) , (this_msg[101])
      , (this_msg[84]) , (this_msg[67]) , (this_msg[50]) , (this_msg[33]) , (this_msg[16])};
  wire [63:0] nl_data_addr_rsci_d;
  assign nl_data_addr_rsci_d = {(this_msg[134:127]) , (this_msg[117:110]) , (this_msg[100:93])
      , (this_msg[83:76]) , (this_msg[66:59]) , (this_msg[49:42]) , (this_msg[32:25])
      , (this_msg[15:8])};
  wire [63:0] nl_data_data_rsci_d;
  assign nl_data_data_rsci_d = {(this_msg[126:119]) , (this_msg[109:102]) , (this_msg[92:85])
      , (this_msg[75:68]) , (this_msg[58:51]) , (this_msg[41:34]) , (this_msg[24:17])
      , (this_msg[7:0])};
  mgc_out_dreg_v2 #(.rscid(32'sd215),
  .width(32'sd1)) data_type_val_rsci (
      .d(nl_data_type_val_rsci_d[0:0]),
      .z(data_type_val_rsc_z)
    );
  mgc_out_dreg_v2 #(.rscid(32'sd216),
  .width(32'sd8)) data_valids_rsci (
      .d(nl_data_valids_rsci_d[7:0]),
      .z(data_valids_rsc_z)
    );
  mgc_out_dreg_v2 #(.rscid(32'sd217),
  .width(32'sd64)) data_addr_rsci (
      .d(nl_data_addr_rsci_d[63:0]),
      .z(data_addr_rsc_z)
    );
  mgc_out_dreg_v2 #(.rscid(32'sd218),
  .width(32'sd64)) data_data_rsci (
      .d(nl_data_data_rsci_d[63:0]),
      .z(data_data_rsc_z)
    );
  mgc_out_dreg_v2 #(.rscid(32'sd219),
  .width(32'sd1)) return_rsci (
      .d(this_val),
      .z(return_rsc_z)
    );
  ccs_in_v1 #(.rscid(32'sd322),
  .width(32'sd1)) ccs_ccore_start_rsci (
      .dat(ccs_ccore_start_rsc_dat),
      .idat(ccs_ccore_start_rsci_idat)
    );
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      this_rdy <= 1'b0;
    end
    else if ( ccs_ccore_start_rsci_idat | asn_itm_1 ) begin
      this_rdy <= ccs_ccore_start_rsci_idat;
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      asn_itm_1 <= 1'b0;
    end
    else begin
      asn_itm_1 <= ccs_ccore_start_rsci_idat;
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    Connections_Combinational_ArbitratedScratchpad_InputSetup_InputType_256U_8U_8U_0U_req_t_Connections_SYN_PORT_PopNB
// ------------------------------------------------------------------


module Connections_Combinational_ArbitratedScratchpad_InputSetup_InputType_256U_8U_8U_0U_req_t_Connections_SYN_PORT_PopNB
    (
  this_val, this_rdy, this_msg, data_type_val_rsc_z, data_valids_rsc_z, data_addr_rsc_z,
      data_data_rsc_z, return_rsc_z, ccs_ccore_start_rsc_dat, ccs_MIO_clk, ccs_MIO_arst
);
  input this_val;
  output this_rdy;
  input [136:0] this_msg;
  output data_type_val_rsc_z;
  output [7:0] data_valids_rsc_z;
  output [63:0] data_addr_rsc_z;
  output [63:0] data_data_rsc_z;
  output return_rsc_z;
  input ccs_ccore_start_rsc_dat;
  input ccs_MIO_clk;
  input ccs_MIO_arst;



  // Interconnect Declarations for Component Instantiations 
  Connections_Combinational_ArbitratedScratchpad_InputSetup_InputType_256U_8U_8U_0U_req_t_Connections_SYN_PORT_PopNB_core
      Connections_Combinational_ArbitratedScratchpad_InputSetup_InputType_256U_8U_8U_0U_req_t_Connections_SYN_PORT_PopNB_core_inst
      (
      .this_val(this_val),
      .this_rdy(this_rdy),
      .this_msg(this_msg),
      .data_type_val_rsc_z(data_type_val_rsc_z),
      .data_valids_rsc_z(data_valids_rsc_z),
      .data_addr_rsc_z(data_addr_rsc_z),
      .data_data_rsc_z(data_data_rsc_z),
      .return_rsc_z(return_rsc_z),
      .ccs_ccore_start_rsc_dat(ccs_ccore_start_rsc_dat),
      .ccs_MIO_clk(ccs_MIO_clk),
      .ccs_MIO_arst(ccs_MIO_arst)
    );
endmodule



