// ----------------------------------------------------------------------------
// SystemC Wrapper for Catapult Design HDL Netlist
//
//    HLS version: 10.4b/841621 Production Release
//       HLS date: Thu Oct 24 17:20:07 PDT 2019
//  Flow Packages: HDL_Tcl 8.0a, SCVerify 10.4
//
//   Generated by: billyk@cad.eecs.harvard.edu
// Generated date: Fri Apr 17 21:42:15 EDT 2020
//
// ----------------------------------------------------------------------------
#ifndef INCLUDED_CCS_DUT_WRAPPER_H
#define INCLUDED_CCS_DUT_WRAPPER_H

#ifndef SC_USE_STD_STRING
#define SC_USE_STD_STRING
#endif

#include <systemc.h>
#include <mc_simulator_extensions.h>

#ifdef CCS_SYSC
namespace HDL {
#endif

#if defined(CCS_DUT_SYSC)

// alias ccs_DUT_wrapper to namespace enclosure of either cycle or RTL SystemC netlist
namespace ccs_design {
#if defined(CCS_DUT_CYCLE)
//#include "cycle.cxx"
#include "cycle.cxx"
#else
#if defined(CCS_DUT_RTL)
//#include "rtl.cxx"
#include "rtl.cxx"
#endif
#endif
}
typedef ccs_design::HDL::SysPE_rtl ccs_DUT_wrapper;

#else

// Create a foreign module wrapper around the HDL
#ifdef VCS_SYSTEMC
// VCS support - ccs_DUT_wrapper is derived from VCS-generated SystemC wrapper around HDL code

class ccs_DUT_wrapper : public TOP_HDL_ENTITY
{
public:
   ccs_DUT_wrapper(const sc_module_name& nm, const char *hdl_name)
      : TOP_HDL_ENTITY(nm)
      {
          //elaborate_foreign_module(hdl_name);
      }
   
   ~ccs_DUT_wrapper() {}
};

#else
// non VCS simulators - ccs_DUT_wrapper is derived from mc_foreign_module (adding 2nd ctor arg)

class ccs_DUT_wrapper : public mc_foreign_module
{
public:
   #ifndef VCS_SYSTEMC
   // Interface Ports
   sc_in<bool> clk;
   sc_in< sc_logic > rst;
   sc_in< sc_logic > weight_in_val;
   sc_out< sc_logic > weight_in_rdy;
   sc_in< sc_lv<8> > weight_in_msg;
   sc_in< sc_logic > act_in_val;
   sc_out< sc_logic > act_in_rdy;
   sc_in< sc_lv<8> > act_in_msg;
   sc_in< sc_logic > accum_in_val;
   sc_out< sc_logic > accum_in_rdy;
   sc_in< sc_lv<32> > accum_in_msg;
   sc_out< sc_logic > act_out_val;
   sc_in< sc_logic > act_out_rdy;
   sc_out< sc_lv<8> > act_out_msg;
   sc_out< sc_logic > accum_out_val;
   sc_in< sc_logic > accum_out_rdy;
   sc_out< sc_lv<32> > accum_out_msg;
   sc_out< sc_logic > weight_out_val;
   sc_in< sc_logic > weight_out_rdy;
   sc_out< sc_lv<8> > weight_out_msg;
   #endif
   
public:
   ccs_DUT_wrapper(const sc_module_name& nm, const char *hdl_name)
      : mc_foreign_module(nm,hdl_name)
      #ifndef VCS_SYSTEMC
      ,clk("clk")
      ,rst("rst")
      ,weight_in_val("weight_in_val")
      ,weight_in_rdy("weight_in_rdy")
      ,weight_in_msg("weight_in_msg")
      ,act_in_val("act_in_val")
      ,act_in_rdy("act_in_rdy")
      ,act_in_msg("act_in_msg")
      ,accum_in_val("accum_in_val")
      ,accum_in_rdy("accum_in_rdy")
      ,accum_in_msg("accum_in_msg")
      ,act_out_val("act_out_val")
      ,act_out_rdy("act_out_rdy")
      ,act_out_msg("act_out_msg")
      ,accum_out_val("accum_out_val")
      ,accum_out_rdy("accum_out_rdy")
      ,accum_out_msg("accum_out_msg")
      ,weight_out_val("weight_out_val")
      ,weight_out_rdy("weight_out_rdy")
      ,weight_out_msg("weight_out_msg")
      #endif
      {
          elaborate_foreign_module(hdl_name);
      }
      
      ~ccs_DUT_wrapper() {}
   };
   #endif
   
   #endif

#endif

#ifdef CCS_SYSC
} // end namespace HDL
#endif

